export const SETVIEW = 'SET_VIEW';
export const UPDATE_SORT = 'UPDATE_SORT';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'
export const GET_PRODUCTS_BEGIN = 'GET_PRODUCTS_BEGIN'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'